config/routes.rb
Ca::Application.routes.draw do
  root :to => 'welcome#index'
  mount Ckeditor::Engine => '/ckeditor'

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config


  match 'novelties' => 'novelties#index', :as => :novelties
  match 'novelties/:id' => 'novelties#index', :as => :novelties_with_cat
  match 'novelty/:id' => 'novelties#show', :as => :novelty

  match 'page/:menu_url/:name_url' => 'welcome#page', :as => :page
  match 'menu/:name_url' => 'welcome#menu', :as => :menu
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_presence :data

  def url_content
    url(:content)
  end
end

app/models/menu_down.rb
#coding: utf-8
#encoding: utf-8
class MenuDown < ActiveRecord::Base
  validates :name, :presence => true
  validates :menu_up, :presence => true
  validates :page, :presence => true
  belongs_to :page
  belongs_to :menu_up
  attr_accessible :name, :name_url, :page_id, :menu_up_id, :sort, :url, :external_url
  def name=(value)
    write_attribute :name_url, (Russian.translit(value).gsub(" ", "_").gsub(".","_dot_"))
    write_attribute :name, (value)
  end
end

app/models/menu_up.rb
#coding: utf-8
#encoding: utf-8
class MenuUp < ActiveRecord::Base
  validates :name, :presence => true
  default_scope :order => :sort
  has_many :menu_downs
  attr_accessible :name, :name_url, :body, :sort, :url, :external_url
  def name=(value)
    write_attribute :name_url, (Russian.translit(value).gsub(" ", "_").gsub(".","_dot_"))
    write_attribute :name, (value)
  end
  def self.repair_sort( begin_sort, end_sort, forward)
    sort_sql=""
    sort_sql += "#{sort_sql == "" ? "" : " and "}sort<=#{end_sort} " unless end_sort.nil?
    sort_sql += "#{sort_sql == "" ? "" : " and "}sort>=#{begin_sort} " unless begin_sort.nil?
    update_all((forward)?"sort=sort+1":"sort=sort-1",sort_sql)
  end
  def initialize(*params)
    super(*params)
    if (@new_record)
      sort = MenuUp.maximum('sort')
      self.sort = (sort.nil?) ? 0 : sort+1
    end
  end
  def resort_all
    old_sort=self.sort
    MenuUp.repair_sort(old_sort, nil, false)
  end
end

app/models/novelty.rb
class Novelty < ActiveRecord::Base
  has_attached_file :image, :styles => {:thumb => "100x100>", :for_main => "200x140>" }
  attr_accessible :title, :image, :preview, :body, :show_status, :novelty_category_id, :cool_news
  belongs_to :novelty_category
end

app/models/novelty_category.rb
class NoveltyCategory < ActiveRecord::Base
  attr_accessible :title, :show_on_footer, :sort
  has_many :novelties
  default_scope :order => :sort
  def self.repair_sort( begin_sort, end_sort, forward)
    sort_sql=""
    sort_sql += "#{sort_sql == "" ? "" : " and "}sort<=#{end_sort} " unless end_sort.nil?
    sort_sql += "#{sort_sql == "" ? "" : " and "}sort>=#{begin_sort} " unless begin_sort.nil?
    update_all((forward)?"sort=sort+1":"sort=sort-1",sort_sql)
  end
  def initialize(*params)
    super(*params)
    if (@new_record)
      sort = NoveltyCategory.maximum('sort')
      self.sort = (sort.nil?) ? 0 : sort+1
    end
  end
  def resort_all
    old_sort=self.sort
    NoveltyCategory.repair_sort(old_sort, nil, false)
  end
end

app/models/page.rb
#coding: utf-8
#encoding: utf-8
class Page < ActiveRecord::Base
  # attr_accessible :title, :body
  validates :name, :presence => true
  has_many :menu_downs
  attr_accessible :name, :name_url, :body, :show_above_main
  def name=(value)
    write_attribute :name_url, (Russian.translit(value).gsub(" ", "_").gsub(".","_dot_"))
    write_attribute :name, (value)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/novelties_controller.rb
#coding: utf-8
#encoding: utf-8
class NoveltiesController < ApplicationController
  def index
    cat_temp = NoveltyCategory.order(:sort).first
    unless cat_temp
      redirect_to root_path
      return
    end
    cat_id = (params[:id].to_i > 0 ? params[:id].to_i : cat_temp.id)
    @novelties = Novelty.where(:show_status => true, :novelty_category_id => cat_id).paginate(:per_page => 10, :page => params[:page])
  end
  def show
    @novelty = Novelty.find_by_id(params[:id])
    unless @novelty
      redirect_to root_path
      return
    end
  end
end

app/controllers/welcome_controller.rb
#coding: utf-8
#encoding: utf-8
class WelcomeController < ApplicationController
  def index
  end
  def page
    @page = Page.where(:name_url => params[:name_url]).first
    if params[:menu_url].to_s == "main"
      @menu = nil
    else
      @menu = MenuDown.where(:name_url => params[:menu_url]).first
    end
  end
  def menu
    @menu = MenuUp.where(:name_url => params[:name_url]).first
    unless @menu
      redirect_to root_path
      return
    end
  end
end

app/helpers/application_helper.rb
# coding: utf-8
module ApplicationHelper
  def meta_title(title)
    content_for :meta_title do; title; end;
  end
  def menu(options = {})
     content_for(:menu, render( :partial => "menu/menu", :locals => {:options => options} ))
  end
end

app/helpers/novelties_helper.rb
module NoveltiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="EN" lang="EN" dir="ltr">
<head profile="http://gmpg.org/xfn/11">
<title><%= yield :meta_title %></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="imagetoolbar" content="no" />
<%= stylesheet_link_tag    "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
</head>
<body>
<div class="wrapper col0">
  <div id="topbar">
    <div id="slidepanel">
      <div class="topbox">
        <h2>ТУСУР</h2>
        <p>ТУСУР – самый молодой из томских университетов, но никогда не был в тени. Созданный во времена прорыва в космос, бурного развития электронно-вычислительной техники, новых средств связи и радиоэлектроники вуз с первых лет своего существования находился на острие научно-технического прогресса. ТИРиЭТ, ТИАСУР, ТАСУР, ТУСУР: как бы он ни назывался, - это марка лидера. Лидера в сфере подготовки квалифицированных кадров для высокотехнологичных отраслей экономики, внедрения инновационных образовательных и исследовательских программ, прикладных разработок новой техники, аппаратуры и систем управления.</p>
        <p class="readmore"><a href="#">Далее &raquo;</a></p>
      </div>
      <div class="topbox">
        <h2>Вход для преподавателя</h2>
        <form action="#" method="post">
          <fieldset>
            <legend>Форма входа преподавателя</legend>
            <label for="teachername">Логин:
              <input type="text" name="teachername" id="teachername" value="" />
            </label>
            <label for="teacherpass">Пароль:
              <input type="password" name="teacherpass" id="teacherpass" value="" />
            </label>
            <label for="teacherremember">
              <input class="checkbox" type="checkbox" name="teacherremember" id="teacherremember" checked="checked" />
              Запомнить меня</label>
            <p>
              <input type="submit" name="teacherlogin" id="teacherlogin" value="Login" />
              &nbsp;
              <input type="reset" name="teacherreset" id="teacherreset" value="Reset" />
            </p>
          </fieldset>
        </form>
      </div>
      <div class="topbox last">
        <h2>Вход для студентов</h2>
        <form action="#" method="post">
          <fieldset>
            <legend>Вход для студентов</legend>
            <label for="pupilname">Логин:
              <input type="text" name="pupilname" id="pupilname" value="" />
            </label>
            <label for="pupilpass">Пароль:
              <input type="password" name="pupilpass" id="pupilpass" value="" />
            </label>
            <label for="pupilremember">
              <input class="checkbox" type="checkbox" name="pupilremember" id="pupilremember" checked="checked" />
              Remember me</label>
            <p>
              <input type="submit" name="pupillogin" id="pupillogin" value="Login" />
              &nbsp;
              <input type="reset" name="pupilreset" id="pupilreset" value="Reset" />
            </p>
          </fieldset>
        </form>
      </div>
      <br class="clear" />
    </div>
    <div id="loginpanel">
      <ul>
        <li class="left">Вход &raquo;</li>
        <li class="right" id="toggle"><a id="slideit" href="#slidepanel">Сотрудники</a><a id="closeit" style="display: none;" href="#slidepanel">Закрыть</a></li>
      </ul>
    </div>
    <br class="clear" />
  </div>
</div>
<!-- ####################################################################################################### -->
<div class="wrapper col1">
  <div id="header">
    <div id="logo">
      <h1><a href="#">Кафедра Системного Анализа</a></h1>
      <p>Факультет Моделирования Систем</p>
    </div>
    <div class="fl_right">
      <ul>
        <li class="last"><a href="#">Поиск</a></li>
        <li><a href="#">Онлайн поддержка</a></li>
        <li><a href="http://timetable.tusur.ru/faculties/fms">Расписание</a></li>
      </ul>
      <p>Тел: xxxxx xxxxxxxxxx | Mail: info@domain.com</p>
    </div>
    <br class="clear" />
  </div>
</div>
<!-- ####################################################################################################### -->
<%= yield :menu %>

<!-- ####################################################################################################### -->
<%= yield  %>
<div class="wrapper col5">
  <div id="footer">
    <div id="newsletter">
      <h2>Не теряй головы !</h2>
      <p>Заполните e-mail и подпишитесь на новости</p>
      <form action="#" method="post">
        <fieldset>
          <legend>Лента новостей</legend>
          <input type="text" value="Введите e-mail здесь&hellip;"  onfocus="this.value=(this.value=='Введите e-mail здесь&hellip;')? '' : this.value ;" />
          <input type="submit" name="news_go" id="news_go" value="GO" />
        </fieldset>
      </form>
      <p>Для разъяснений <a href="#">кликните здесь &raquo;</a></p>
    </div>

      <% temp = NoveltyCategory.where(:show_on_footer => true).order(:sort).reverse! %>
      <% temp.each do |category| %>
        <div class="footbox">
          <h2><%= link_to category.title, novelties_with_cat_path(category.id) %></h2>
          <ul>
            <% category.novelties.each_with_index do |novelty, index| %>
              <li class="<%= index+1 == category.novelties.size ? "last" : "" %>"><%= link_to novelty.title, novelty_path(novelty.id) %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <br class="clear" />
  </div>
</div>

<!-- ####################################################################################################### -->
<div class="wrapper col6">
  <div id="copyright">
    <p class="fl_left">&copy; 2013 - Кафедра Системного Анализа - <a href="#">ТУСУР</a></p>
    <br class="clear" />
  </div>
</div>
</body>
</html>

app/views/menu/_menu.html.erb
<div class="wrapper col2">
  <div id="topnav">
    <ul>
      <li class="<%= options[:current] == "root" ? "active" : "" %>"><%= link_to "Главная", root_path %>
        <ul>
          <% temp_page = Page.where(:show_above_main => true) %>
          <% temp_page.each_with_index do |page, index| %>
              <li class=<%= index+1 == temp_page.size ? "last" : "" %>><%= link_to page.name, page_path("main",page.name_url) %></li>
          <% end %>
        </ul>
      </li>
      <li class="<%= options[:current] == "novelties" ? "active" : "" %>"><%= link_to "Новости", novelties_path %>
        <ul>
          <% temp = NoveltyCategory.order(:sort) %>
          <% temp.each_with_index do |category, index| %>
            <li class="<%= index+1 == temp.size ? "last" : "" %>"> <%= link_to category.title, novelties_with_cat_path(category.id) %> </li>
          <% end %>
        </ul>
      </li>
      <% menu_temp = MenuUp.order(:sort) %>
      <% menu_temp.each_with_index do |menu, index| %>
          <% my_class = (index+1 == menu_temp.size ? "last" : "") %>
          <% my_class += (options[:current_url] == menu.name_url ? "active" : "") %>
        <li class="<%= my_class %>">
          <% if menu.external_url %>
            <%= link_to menu.name, menu.url %>
          <% else %>
            <%= link_to menu.name, menu_path(menu.name_url) %>
          <% end %>
          <% unless menu.menu_downs.empty? %>
            <ul>
              <% menu_down_temp = menu.menu_downs.order(:sort) %>
              <% menu_down_temp.each_with_index do |down, index| %>
                <li class=<%= index+1 == menu_down_temp.size ? "last" : "" %>>
                  <% if down.external_url %>
                    <%= link_to down.name, down.url %>
                  <% else %>
                    <%= link_to down.name, page_path(down.name_url,down.page.name_url) %>
                  <% end %>
                </li>
              <% end %>
            </ul>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/novelties/index.html.erb
<%= meta_title("Новости") %>
<%menu :current => "novelties"%>
<h1>Новосточки</h1>

<% @novelties.each do |novelty| %>
    <%= link_to novelty.title, novelty_path(novelty.id) %>
    <%= link_to (image_tag novelty.image.url(:thumb)), novelty_path(novelty.id) %>
    <%= novelty.preview.html_safe %>
    <br/>
<% end %>

app/views/novelties/show.html.erb
<%= meta_title(@novelty.title) %>
<%menu :current => "novelties"%>
<h1><%= @novelty.title %></h1>

<%= image_tag @novelty.image.url(:original) %>
<%= @novelty.preview.html_safe %>
<%= @novelty.body.html_safe %>

app/views/welcome/index.html.erb
<%= meta_title("Кафедра Системного Анализа - Томский Университет Систем Управления и Радиоэлектроники") %>
<%menu :current => "root"%>

<!-- ####################################################################################################### -->
<div class="wrapper col3">
  <div id="featured_slide">
    <div id="featured_wrap">
      <ul id="featured_tabs">
        <li><a href="#fc1">Картинка о кафедре<br />
          <span>Что-нибудь интересное и поучительное.</span></a></li>
        <li><a href="#fc2">Картинка о кафедре<br />
          <span>Что-нибудь интересное и поучительное.</span></a></li>
        <li><a href="#fc3">Картинка о кафедре<br />
          <span>Что-нибудь интересное и поучительное.</span></a></li>
        <li class="last"><a href="#fc4">Картинка о кафедре<br />
          <span>Что-нибудь интересное и поучительное.</span></a></li>
      </ul>
      <div id="featured_content">
        <div class="featured_box" id="fc1"><img src="/assets/demo/1.gif" alt="" />
          <div class="floater"><a href="#">Далее &raquo;</a></div>
        </div>
        <div class="featured_box" id="fc2"><img src="/assets/demo/2.gif" alt="" />
          <div class="floater"><a href="#">Далее &raquo;</a></div>
        </div>
        <div class="featured_box" id="fc3"><img src="/assets/demo/3.gif" alt="" />
          <div class="floater"><a href="#">Далее &raquo;</a></div>
        </div>
        <div class="featured_box" id="fc4"><img src="/assets/demo/4.gif" alt="" />
          <div class="floater"><a href="#">Далее &raquo;</a></div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- ####################################################################################################### -->
<div class="wrapper col4">
  <div id="container">
    <div id="hpage">
      <ul>
        <% temp_news = Novelty.where(:show_status => true, :cool_news => true).order("rand()").limit(4) %>
        <% temp_news.each_with_index do |news, index| %>
          <li class=<%= index+1 == temp_news.size ? "last" : "" %>>
            <h2><%= news.title %> </h2>
            <div class="imgholder"><%= link_to (image_tag news.image.url(:for_main)), novelty_path(news.id) %></div>
            <p><%= strip_tags(news.preview).html_safe.truncate(200) %></p>
            <p class="readmore"><%= link_to "Далее", novelty_path(news.id) %></p>
          </li>
        <% end %>
      </ul>
      <br class="clear" />
    </div>
  </div>
</div>

app/views/welcome/menu.html.erb
<%= meta_title(@menu.name) %>
<%menu :current => "pages", :current_url => @menu.name_url%>
<h1><%= @menu.name %></h1>
<%= @menu.body.html_safe %>

app/views/welcome/page.html.erb
<% if @menu %>
    <%= meta_title(@menu.name) %>
    <%menu :current => "pages", :current_url => @menu.menu_up.name_url%>
<% else %>
    <%= meta_title(@page.name) %>
   <%menu :current => "root"%>
<% end %>
<h1><%= (@menu ? @menu.name : @page.name) %></h1>
<%= @page.body.html_safe %>